---
- name: Add i386 architecture
  command: dpkg --add-architecture i386

- name: Install packages
  apt:  pkg={{ item }}
        state=latest
        update_cache=yes
  with_items:
    - bc
    - build-essential
    - cron
    - curl
    - gcc-5
    - gcc-5-plugin-dev
    - gcc-arm-linux-gnueabi
    - git-core
    - htop
    - libelf-dev
    - libgcc1:i386
    - libncurses5:i386
    - libssl-dev
    - libstdc++6:i386
    - lzop
    - msmtp
    - openjdk-8-jre-headless
    - python
    - python-keyring
    - unzip
    - zlib1g:i386
  tags:
    - install
    - packages

- include: compilers.yml
- include: users.yml
- include: mirrors.yml
