---
- name: Craete the build group
  group:
    name: buildslave
    state: present
  tags:
    - install
    - user

- name: Create the build user
  user:
    name: buildslave
    group: buildslave
    home: /home/buildslave
    shell: /bin/bash
    state: present
    system: yes
  tags:
    - install
    - user
